app_id: B9F6E402-0CAE-4045-BDE6-14BD6C39C4EA
publisher: Technical White Hat
publisher_url: https://github.com/technicalwhitehat-yt/RhyThm-Music
display_name: RhyThm Music
create_desktop_icon: true
privileges_required: lowest
script_template: inno_setup.iss
locales:
  - en