name: Build Android apk
on: workflow_dispatch

jobs:
  build-android-apk:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the RhyThm-Music repository
      - name: Checkout RhyThm-Music project
        uses: actions/checkout@v4
        with:
          repository: 'technicalwhitehat-yt/RhyThm-Music'

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.2'

      # Step 3: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      # Step 4: Run flutter doctor
      - name: Flutter doctor
        run: flutter doctor
        
      # ⭐️ NEW STEP: Fix pubspec.yaml name ⭐️
      - name: Fix pubspec.yaml name
        run: |
          (Get-Content pubspec.yaml).replace('name: rhythm-music', 'name: rhythm_music') | Set-Content pubspec.yaml
        shell: pwsh

      # Step 5: Install project dependencies
      - name: Install project dependencies
        run: flutter pub get

      # Step 6: Update language data
      - name: Update lang data
        run: dart localization/generator.dart

      # Step 7: Set update check flag to true
      - name: Set update check flag to true
        run: echo "const updateCheckFlag = true;" > lib/utils/update_check_flag_file.dart
        
      # Step 8: Build Android APK
      - name: Build android apk
        run: flutter build apk --split-per-abi --release

      # Step 9: Upload the generated APKs
      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: RhyThm-music-apk
          path: build/app/outputs/flutter-apk/*release.apk
