name: Build Android apk
on: workflow_dispatch

jobs:
  build-android-apk:
    runs-on: windows-latest

    steps:
      # Step 1: Puraane project ko checkout karein
      - name: Checkout RhyThm-Music project
        uses: actions/checkout@v4
        with:
          repository: 'technicalwhitehat-yt/RhyThm-Music'

      # Step 2: Java Setup karein
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      # Step 3: Flutter Setup karein
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.2'

      # Step 4: Flutter Doctor chalayein
      - name: Flutter doctor
        run: flutter doctor

      # --- Yahaan se Asli Fix Shuru Hota Hai ---

      # Step 5: NDK Version ko Theek Karein (Naya Step)
      - name: Set NDK Version
        run: |
          $buildGradle = "android/app/build.gradle"
          (Get-Content $buildGradle) -replace 'ndkVersion flutter.ndkVersion', 'ndkVersion "26.1.10909125"' | Set-Content $buildGradle
        shell: pwsh

      # Step 6: pubspec.yaml mein naam theek karein
      - name: Fix pubspec.yaml name
        run: |
          (Get-Content pubspec.yaml) -replace 'name: rhythm-music', 'name: rhythm_music' | Set-Content pubspec.yaml
        shell: pwsh

      # Step 7: Saari Dart Files mein Import Paths ko Theek Karein (Sabse Zaroori Naya Step)
      - name: Fix Dart import paths
        run: |
          Get-ChildItem -Path . -Filter *.dart -Recurse | ForEach-Object {
              (Get-Content $_.FullName) -replace 'package:rhythmmusic/', 'package:rhythm_music/' -replace 'package:harmonymusic/', 'package:rhythm_music/' | Set-Content $_.FullName
          }
        shell: pwsh

      # Step 8: Dependencies install karein
      - name: Install project dependencies
        run: flutter pub get

      # Step 9: Bhasha ki data update karein
      - name: Update lang data
        run: dart localization/generator.dart

      # Step 10: APK Build karein
      - name: Build android apk
        run: flutter build apk --split-per-abi --release

      # Step 11: APK ko upload karein
      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: RhyThm-music-apk
          path: build/app/outputs/flutter-apk/*release.apk
