name: Build linux binaries (deb, appimage & rpm)
on: workflow_dispatch

jobs:
  build-linux-deb-appimage-rpm:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Sirf ek baar project ko checkout karein (Ismein aapke saare manual fixes shaamil honge)
      - name: Checkout project
        uses: actions/checkout@v4

      # Step 2: Flutter Setup karein
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.2'

      # Step 3: Linux ke liye zaroori dependencies install karein
      - name: Install required linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmpv-dev mpv libayatana-appindicator3-dev ninja-build libgtk-3-dev rpm patchelf locate libfuse2

      # Step 4: Flutter Doctor chalayein
      - name: Flutter doctor
        run: flutter doctor

      # Step 5: Dependencies install karein (ab working-directory ki zaroorat nahi)
      - name: Install project dependencies
        run: flutter pub get

      # Step 6: Flutter distributor install karein
      - name: Install Flutter distributor
        run: dart pub global activate distributor

      # Step 7: Bhasha ki data update karein
      - name: Update lang data
        run: dart localization/generator.dart

      # Step 8: Update check flag set karein
      - name: Set update check flag to true
        run: echo "const updateCheckFlag = true;" > lib/utils/update_check_flag_file.dart

      # Step 9: Linux binaries build karein
      - name: Build linux deb, appImage & rpm package
        run: distributor package --platform linux --targets deb,rpm,appimage

      # Step 10: Linux binaries ko upload karein
      - name: Upload linux binaries
        uses: actions/upload-artifact@v4
        with:
          name: RhyThm-music-linux-binaries
          path: dist/*
